services:
  - type: web
    name: finance-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BRIDGE_CLIENT_ID
        sync: false
      - key: BRIDGE_CLIENT_SECRET
        sync: false
      - key: BRIDGE_ENV
        value: sandbox